### ISSUE TITLE
Typo in codelab of loss type `categoricalCrossEntropy`

### ISSUE THREAD

**Issue by kangyizhang** [aayusharora/TensorflowJS-NeuralNet#1]
There is a typo in google codelab (https://codelabs.developers.google.com/codelabs/neural-tensorflow-js/index.html?index=..%2F..index#5), the loss type should be `categoricalCrossentropy` (lower case of letter e).

**Comment by aayusharora** [comment]
I think, it is solved now :)
Thanks @kangyizhang
